# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Vehicle.create(type_of_vehicle: 'Airplane', make: 'Boeing', model: '747-430', country: 'Brunei')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'Boeing', model: '767-200', country: 'Brunei')
Vehicle.create(type_of_vehicle: 'Helicopter', make: 'Blackhawk', model: 'UH-60', country: 'Brunei')
Vehicle.create(type_of_vehicle: 'Car', make: 'Mercedes Benz', model: 'G55 AMG', country: 'Brunei')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'Airbus', model: 'A330-200', country: 'France')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'Airbus', model: 'A400M Atlas', country: 'France')
Vehicle.create(type_of_vehicle: 'Jet', make: 'Dassault', model: 'Falcon 7X', country: 'France')
Vehicle.create(type_of_vehicle: 'Car', make: 'Citroën', model: 'DSS Hybrid 4 Landaulet', country: 'France')
Vehicle.create(type_of_vehicle: 'Jet', make: 'Gulfstream', model: 'V', country: 'Equatorial Guinea')
Vehicle.create(type_of_vehicle: 'Jeep', make: 'Lexus', model: 'SUV', country: 'Equatorial Guinea')
Vehicle.create(type_of_vehicle: 'Tank/heavily-armored vehicle', make: 'Pandur', model: 'APC', country: 'Equatorial Guinea')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'Airbus', model: 'A310-304', country: 'Pakistan')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'Lockheed', model: 'C-130 Hercules', country: 'Pakistan')
Vehicle.create(type_of_vehicle: 'Car', make: 'Mercedes Benz', model: 'W221', country: 'Pakistan')
Vehicle.create(type_of_vehicle: 'Jeep', make: 'Toyota', model: 'Land Cruiser', country: 'Pakistan')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'Fokker', model: '50', country: 'Mongolia')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'Boeing', model: '767-300', country: 'Mongolia')
Vehicle.create(type_of_vehicle: 'Animal', make: 'Horse', model: '', country: 'Mongolia')
Vehicle.create(type_of_vehicle: 'Car', make: 'Mercedes', model: 'S-Class', country: 'Mongolia')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'Fokker', model: 'F28', country: 'Argentina')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'Boeing', model: '757', country: 'Argentina')
Vehicle.create(type_of_vehicle: 'Helicopter', make: 'Sikorsky', model: 'S70', country: 'Argentina')
Vehicle.create(type_of_vehicle: 'Car', make: 'Audi', model: 'A8 L', country: 'Argentina')
Vehicle.create(type_of_vehicle: 'Car', make: 'Volkswagen', model: 'Passat CC', country: 'Argentina')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'McDonnell Douglas', model: 'MD-87', country: 'Swaziland')
Vehicle.create(type_of_vehicle: 'Helicopter', make: 'IAI', model: 'Arava', country: 'Swaziland')
Vehicle.create(type_of_vehicle: 'Tank/heavily-armored vehicle', make: 'BAE', model: 'RG-31 Nyala Mark 5E', country: 'Swaziland')
Vehicle.create(type_of_vehicle: 'Car', make: 'Mercedes Benz', model: 'S600', country: 'Swaziland')
Vehicle.create(type_of_vehicle: 'Car', make: 'Maybach', model: '62', country: 'Swaziland')
Vehicle.create(type_of_vehicle: 'Car', make: 'BMW', model: 'X3', country: 'Swaziland')
Vehicle.create(type_of_vehicle: 'Airplane', make: 'Fokker', model: '70 ER', country: 'The Netherlands')
Vehicle.create(type_of_vehicle: 'Train', make: 'NS', model: '6300 Beatrix', country: 'The Netherlands')
Vehicle.create(type_of_vehicle: 'Coach (motor)', make: 'VDL/Kusters', model: 'Royal Coach', country: 'The Netherlands')
Vehicle.create(type_of_vehicle: 'Coach (non-motor)', make: 'Spijker', model: 'Gold Coach', country: 'The Netherlands')
Vehicle.create(type_of_vehicle: 'Car', make: 'Volvo', model: 'S80', country: 'The Netherlands')
